openfisca/legislation-explorer

- README.md
See https://github.com/openfisca/legislation-explorer/issues/24#issuecomment-275348885
> Add a paragraph in the README about openfisca-ops

- src/components/pages/home.jsx
> Display country package version

- config/development.js
- config/production.france.js
- config/production.tunisia.js
- graph/index.html
- package.json
- src/client.jsx
> Add piwik tracking code

- README.md
- graph/index.html
This patch extends #31 continuing using https explicitely.
> Use https explicitely in /graph assets

- package.json
- src/components/pages/variables.jsx
- src/components/search-box.jsx
- src/variables-tree.js
Implements #22 and #23 in a row (was easier).
> Implement search by name in variables page

- package.json
- src/components/search-box.jsx
- src/variables-tree.js
> Implement search by label in variables page

- src/components/pages/parameter.jsx
> Remove consumer variables rendering from parameter page

- circle.yml
- deploy_prod.sh
> Setup continuous deployment

- src/components/app.jsx
- src/components/pages/home.jsx
> Improve CTA discoverability

- src/assets/style.css
- src/components/app.jsx
- src/server/render.jsx
- webpack.config.dev.js
- webpack.config.prod.babel.js
> Add footer and link to github

- package.json
- src/app-prop-types.js
- src/search.js
- src/server/index.js
> Improve the search algorithm

- src/components/pages/home.jsx
- src/search.js
- src/server/index.js
> Improve search results ordering

- src/components/app.jsx
- src/components/pages/home.jsx
- src/components/pages/not-found.jsx
- src/components/pages/parameter-or-variable.jsx
> Change wording of back button and keep search query across navigation

- .eslintignore
- README.md
- package.json
- src/components/app.jsx
- tests/1 - AppScenario.js
- tests/2 - SearchBarScenario.js
- tests/3 - NavigationScenario.js
- tests/AppComponent.js
- tests/AppFixture.js
- tests/DetailsComponent.js
- tests/SearchBarComponent.js
- tests/SearchBarFixture.js
- tests/config.js
> Add integration tests

- circle.yml
- package.json
> Run integration tests in CI

- config/development.js
- config/production.france.js
- package.json
- src/app-prop-types.js
- src/components/app.jsx
- src/components/pages/home.jsx
- src/components/pages/parameter-or-variable.jsx
- src/components/parameter.jsx
- src/components/variable.jsx
- src/search.js
- src/server/index.js
- src/webservices.js
- tests/4 - LookUpParameterScenario.js
- tests/5 - LookUpInterruptedParameterScenario.js
- tests/ParameterTableComponent.js
- tests/ParameterTableFixture.js
- tests/SearchBarFixture.js
- webpack.config.dev.js
> Use new param api

- README.md
Adds install information for first time user.
> Explain where npm should be runned

- circle.yml
- package.json
- src/assets/style.css
- src/components/app.jsx
- src/components/pages/swagger.jsx
- src/routes.jsx
- src/server/index.js
- src/server/render.jsx
- src/webservices.js
- webpack.config.dev.js
- webpack.config.prod.babel.js
Connected openfisca/openfisca-core#514
> Document the preview API in the legislation explorer

- src/components/app.jsx
> Don't reload the page

- package.json
Connected to openfisca/openfisca-core#520
> Upgrade swagger to display error responses body

- package.json
- src/components/pages/parameter-or-variable.jsx
- src/components/variable.jsx
- src/config.js
- tests/integration/2 - SearchBarScenario.js
- tests/integration/3 - LookUpVariableScenario.js
- tests/integration/VariableComponent.js
- tests/integration/VariableFixture.js
- tests/unit/formulas.js
Connected to #98 
In a variable page, replace any reference to an OpenFisca variable by a link to its page.
> Clickable variable names 98

- README.md
- src/components/variable.jsx
Connected to openfisca/openfisca-doc#89
> Reference the new address of the documentation

- package.json
Connected to https://github.com/openfisca/openfisca-core/issues/559.
> Improve package metadata

- config/production.france.js
- package.json
Connected to openfisca/openfisca-core#570
This PR changes the URL to reach the Openfisca API
> Change url to the API

- circle.yml
- src/components/variable.jsx
> Fix formula rendering

- README.md
- circle.yml
- package.json
- src/assets/lang/en.json
- src/assets/lang/fr.json
- src/assets/style.css
- src/components/variable.jsx
- tests/integration/7 - LookUpEnumVariableScenario.js
- tests/integration/VariableComponent.js
- tests/integration/VariableFixture.js
Connected to openfisca/openfisca-france#831
A enum variable page now displays a keyword/description table to indicate to users which keyword they should choose.
> Display new Enums in variable pages

- README.md
- src/components/app.jsx
- src/components/variable.jsx
Thanks to https://github.com/openfisca/openfisca.org/issues/30.
Fixes #142
> Switch OpenFisca.org links to HTTPS

- .eslintrc
- package.json
- src/assets/style.css
- src/components/app.jsx
- src/components/formula.jsx
- src/components/pages/parameter-or-variable.jsx
- src/components/pages/swagger.jsx
- src/components/parameter.jsx
- src/components/scale.jsx
- src/components/variable.jsx
- src/config.js
- src/search.js
- src/server/html-document.jsx
- src/server/index.js
- src/server/render.jsx
Upgrade ESlint and remove obsolete dependency.
> Unify indentation and semicolons usage

- package-lock.json
- package.json
- src/components/scale.jsx
- src/server/render.jsx
+ knight because there are already too many PRs open: minor refactor in assets loading.
> Remove unused dependency

- .gitignore
- package.json
- webpack.config.prod.babel.js
See https://github.com/openfisca/legislation-explorer/pull/171 for issue description
> Take .env into account when building webpack for prod 

- .eslintrc
- src/assets/lang/en.json
- src/assets/lang/fr.json
- src/assets/style.css
- src/components/formula.jsx
- src/components/pages/parameter-or-variable.jsx
- src/server/webpack-dev-server.js
- src/webservices.js
- webpack.config.dev.js
- webpack.config.prod.babel.js
> Display an error message when the API doesn't respond

- .circleci/config.yml
Connected to openfisca/openfisca-ops#60
Depends on https://github.com/openfisca/openfisca-ops/pull/61
It works: https://circleci.com/gh/openfisca/legislation-explorer/714
> Re-add continuous deployment

- package.json
- tests/integration/config-ci.js
- webpack.config.dev.js
- webpack.config.prod.babel.js
Depends on #188 
What's working:
- `npm run dev` locally
- `npm run build && npm start` locally
- integration tests for Chrome, Firefox and IE _most of the time_
~What's not working:~
- ~Integration tests for Android are _really_ slow and [always get stuck](https://circleci.com/gh/openfisca/legislation-explorer/743#queue-placeholder/containers/3) trying to load a scale page. Could not reproduce in a live test environment in saucelabs.~
~If anyone has ideas, time and motivation to try to deliver this, I'm running out of all of them...~
EDIT: It works after upgrading Android in integration tests.
> Upgrade webpack

- src/server/index.js
- src/server/render.jsx
This *seems* to fix the problem, I'd feel better if we also had a unit test against this. On the other hand, this is a production bug so I'd prefer not to delay too long if we don't already have ways in place for checking this kind of property.
Fixes #202
> Use configured basename in server-side rendering

- src/assets/style.css
Fixes #159 
Tested via SauceLabs "video" on Android emulated device. (This isn't ideal… I'm yearning for review apps.)
> Fix text flow problem in country package info
