openfisca/legislation-explorer

- graph/main.js
As a user,
I can go to https://legislation.openfisca.fr/graph/
Without provoking an exception.
`revdisp` is currently the root node of the displayed tree.
It needs to be renamed to `revenu_disponible` to fix the bug.
> Rename revdisp to revenu_disponible in graph page

- .gitignore
Some people use the [Visual Studio Code](https://github.com/Microsoft/vscode) editor, which writes a `.vscode` directory relative to each project, containing the specific configuration for the project.
This patch simply ignores this dir.
> Ignore Visual Studio Code config directory

- package.json
- src/components/pages/home.jsx
The "linter" npm script was renamed to "lint" to follow the conventions used in the NodeJS community.
> Fix lint errors

- src/config.js
Configuration has no reason to be printed.
> Do not log config at application start

- package.json
Connected to #37 
CircleCI infers that this is a NodeJS project, so for now there is no need to commit a `circle.yml` file. Providing `npm test` in `package.json` suffices.
> Add continuous integration

- src/app-prop-types.js
Precedes #59 
In order to keep PRs atomic, I create this one dedicated to fix a warning I didn't see during development:
```
[0] Warning: Failed prop type: Invalid prop `parameters[749]` supplied to `HomePage`.
[0]     in HomePage (created by RouterContext)
[0]     in RouterContext
[0]     in IntlProvider
[0] Warning: Failed prop type: Invalid prop `parameters[749]` supplied to `App`.
[0]     in App (created by RouterContext)
[0]     in RouterContext
[0]     in IntlProvider
```
The prop-types system is specific to React and overlaps with a type-checking system; but it's here so better fix it.
> Make Parameter and Scale description not required anymore

- deploy_prod.sh
This improves resilience of continuous deployment script (introduced in #50), in the case there is a need to update the dependencies.
> I could have added a `npm install` line in [deploy_prod.sh](https://github.com/openfisca/legislation-explorer/blob/master/deploy_prod.sh) before `npm run build`, but the `prebuild` script is less specific.
> Update dependencies before build in deployment script

- config/development.js
- config/production.france.js
- package.json
- src/server/index.js
- webpack.config.dev.js
- webpack.config.prod.babel.js
Connected to #86.
To test the logging, I added some code intended to fail here : https://github.com/openfisca/legislation-explorer/blob/master/src/server/render.jsx#L15 :
```js
var a
a.b
```
Console output is : 
```
[0] Server listening at http://localhost:2030/
[0] error: Error on request GET /
[0] TypeError: Cannot read property 'b' of undefined
[0]     at /data/projects/openfisca/legislation-explorer/src/server/render.jsx:16:5
[0]     at Layer.handle [as handle_request] (/data/projects/openfisca/legislation-explorer/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/data/projects/openfisca/legislation-explorer/node_modules/express/lib/router/index.js:317:13)
[0]     at /data/projects/openfisca/legislation-explorer/node_modules/express/lib/router/index.js:284:7
[0] …
```
> Replace errors emailing by logging

- src/components/variable.jsx
Connected to #107 
This PR corrects 
- the "Get the JSON for this variable" broken link
- the "target=_blank" and the end of references
- the space around variables in the formula
> Fix spaces and broken links

- README.md
- src/assets/lang/en.json
- src/assets/lang/fr.json
- src/components/pages/home.jsx
- src/components/pages/not-found.jsx
- src/components/pages/parameter-or-variable.jsx
- src/components/pages/searchbar.jsx
Connected to #83
This PR should add the following behavior : 
the user types : legislation.openfisca.fr/fakename
--> they are redirected on the homepage, with an info message and a search for 'fakename' already processed
the user types  legislation.openfisca.fr/fakename/faky
--> they are directed to a dedicated 404 page with a seach bar that has not been populated. On submit, this search bar directs them to the homepage with the search they entered processed.
Finally, I tried to clarify the integration test part of the read me.
-----
EDIT by @fpagnoux: Add reference issue
> Enhance 404 pages

- config/production.france.js
- package.json
The API calls must be done in HTTPS if we want to serve the legislation explorer in HTTPS.
Connected to openfisca/openfisca-core#572
> Use HTTPS for the API

- src/components/parameter.jsx
Fixes #125 
On parameter pages, update titles to:
* remove invisible spaces before dots
* break long titles on multiple lines
* keep an easy copy/paste of the parameter id
> Remove invisible spaces from parameters' titles

- package.json
Update reference from v18 to v20 to be used as the API version for development.
> Use API v20 for development

- README.md
- deploy_prod.sh
- package.json
- src/client.jsx
- src/components/pages/parameter-or-variable.jsx
- src/components/pages/searchbar.jsx
- src/server/render.jsx
- webpack.config.prod.babel.js
Connected to openfisca/openfisca-ops#13
To add with a basename, example fr.openfisca.org/legislation:
```
BASEPATH=/legislation npm run build
BASEPATH=/legislation node index.js
```
~Test with https://fr.openfisca.org/tmp~
Thanks to @Anna-Livia and @sandcha
> Add option to set a basename

- config/production.france.js
- package.json
Connected to openfisca/openfisca-ops#42.
Move default France API version from v20 to v21.
> Set default OpenFisca France API version to v21

- src/assets/lang/en.json
- src/assets/lang/fr.json
- src/components/parameter.jsx
When a parameter ends, it is represented as a full-width sentence that prevents easy scanning of the date and brings unnecessary complexity in the code.
This changeset unifies the presentation and presents the end as another type of value.
- - - -
Depends on #149.
> Unify ended parameter with standard date changes

- src/assets/style.css
- src/components/pages/parameter-or-variable.jsx
The “loading content” text is hard to spot, making it not obvious when values are loading.
This changeset enlarges and centres the text, and adds a large spinning icon.
- - - -
Depends on #149.
> Increase discoverability of loading indicator

- src/components/app.jsx
- src/components/formula.jsx
- src/components/pages/home.jsx
- src/components/pages/parameter-or-variable.jsx
- src/components/parameter.jsx
- src/components/scale.jsx
- src/components/variable.jsx
- src/openfisca-proptypes.js
- Do not export unused shapes
- Do not `import *`
- Use standard React `shape` suffix for proptypes
> Decrease and standardise proptypes API surface

- package-lock.json
- package.json
fixes #163
Updates the piwik-react-router in order to trak the basename when the app is hosted on a path such as : 
fr.openfisca.org/legislation
> Update piwik tracker

- package.json
- src/client.jsx
- src/components/formula.jsx
- src/server/lang.js
- webpack.config.prod.babel.js
Depends on #187 
_Note: This PR is opened against `error-message` for diff readability, but should be merged on `master`. Target branch should be changed once #187  is merged._
Reduces the bundle size from 2.34MB to 1.47MB (-37%) by:
- Only bundling the used locales (fr and en)
- Only bundling the used syntax coloring (python)
1.47MB is still insanely high... The best way to reduce would be to get Swagger-ui out off the bundle and load in only when visiting the `/swagger` page
> Reduce Bundle size

- src/assets/lang/en.json
- src/assets/lang/fr.json
- src/assets/style.css
- src/components/parameter.jsx
- src/components/variable.jsx
- src/openfisca-proptypes.js
Fixes #124 
Add `Documentation:` field with multiline string value on variable and parameter pages.
On model's variable and parameter:
* Display `Documentation:` field when `documentation` attribute is returned by the web api. 
* And keep new lines.
* Display nothing when `documentation` attribute doesn't exist in web api response.
Note: 
This PR ignores the following API attributes:
* parameter node `documentation` attribute
* variable formula `documentation` attribute
> Add editorial content on variables and parameters 
